//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirLine()
        {
            this.Invoice_Details = new HashSet<Invoice_Details>();
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public string Air_ID { get; set; }
        public string Payable_Code { get; set; }
        public string Payable_Supplier { get; set; }
        public Nullable<decimal> Ticket_Commission { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public int Cat_ID { get; set; }
    
        public virtual Expenses_Category Expenses_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Details> Invoice_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
