//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcCat> AcCats { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AirLine> AirLines { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DailyExpens> DailyExpenses { get; set; }
        public virtual DbSet<Expenses_Category> Expenses_Category { get; set; }
        public virtual DbSet<Income_Stream> Income_Stream { get; set; }
        public virtual DbSet<Invoice_Details> Invoice_Details { get; set; }
        public virtual DbSet<TicketClass> TicketClasses { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<V_Payable> V_Payable { get; set; }
        public virtual DbSet<V_Receiveable> V_Receiveable { get; set; }
    
        public virtual ObjectResult<sp_get_All_Invoice_Result> sp_get_All_Invoice(Nullable<System.DateTime> dfrom, Nullable<System.DateTime> dto, string payStatus)
        {
            var dfromParameter = dfrom.HasValue ?
                new ObjectParameter("Dfrom", dfrom) :
                new ObjectParameter("Dfrom", typeof(System.DateTime));
    
            var dtoParameter = dto.HasValue ?
                new ObjectParameter("Dto", dto) :
                new ObjectParameter("Dto", typeof(System.DateTime));
    
            var payStatusParameter = payStatus != null ?
                new ObjectParameter("PayStatus", payStatus) :
                new ObjectParameter("PayStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_All_Invoice_Result>("sp_get_All_Invoice", dfromParameter, dtoParameter, payStatusParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_get_Balance(Nullable<int> bankCashReceiveable)
        {
            var bankCashReceiveableParameter = bankCashReceiveable.HasValue ?
                new ObjectParameter("BankCashReceiveable", bankCashReceiveable) :
                new ObjectParameter("BankCashReceiveable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_get_Balance", bankCashReceiveableParameter);
        }
    
        public virtual ObjectResult<sp_View_Amount_Payable_Result> sp_View_Amount_Payable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_View_Amount_Payable_Result>("sp_View_Amount_Payable");
        }
    
        public virtual ObjectResult<sp_View_Amount_Receiveable_Result> sp_View_Amount_Receiveable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_View_Amount_Receiveable_Result>("sp_View_Amount_Receiveable");
        }
    
        public virtual ObjectResult<spGet_All_Invoice_Details_Result> spGet_All_Invoice_Details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Invoice_Details_Result>("spGet_All_Invoice_Details");
        }
    
        public virtual ObjectResult<spGet_All_Invoice_DetailsByDateAndPayStatus_Result> spGet_All_Invoice_DetailsByDateAndPayStatus(Nullable<System.DateTime> dfrom, Nullable<System.DateTime> dto, string payStatus)
        {
            var dfromParameter = dfrom.HasValue ?
                new ObjectParameter("Dfrom", dfrom) :
                new ObjectParameter("Dfrom", typeof(System.DateTime));
    
            var dtoParameter = dto.HasValue ?
                new ObjectParameter("Dto", dto) :
                new ObjectParameter("Dto", typeof(System.DateTime));
    
            var payStatusParameter = payStatus != null ?
                new ObjectParameter("PayStatus", payStatus) :
                new ObjectParameter("PayStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_All_Invoice_DetailsByDateAndPayStatus_Result>("spGet_All_Invoice_DetailsByDateAndPayStatus", dfromParameter, dtoParameter, payStatusParameter);
        }
    
        public virtual ObjectResult<spGet_AP_Summary_Result> spGet_AP_Summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_AP_Summary_Result>("spGet_AP_Summary");
        }
    
        public virtual ObjectResult<spGet_AP_SummaryByDate_Result> spGet_AP_SummaryByDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_AP_SummaryByDate_Result>("spGet_AP_SummaryByDate", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spGet_AR_Summary_Result> spGet_AR_Summary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_AR_Summary_Result>("spGet_AR_Summary");
        }
    
        public virtual ObjectResult<spGet_AR_SummaryByDate_Result> spGet_AR_SummaryByDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_AR_SummaryByDate_Result>("spGet_AR_SummaryByDate", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<spGet_BankOrCash_Result> spGet_BankOrCash(Nullable<int> bankID, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var bankIDParameter = bankID.HasValue ?
                new ObjectParameter("BankID", bankID) :
                new ObjectParameter("BankID", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGet_BankOrCash_Result>("spGet_BankOrCash", bankIDParameter, fromDateParameter, toDateParameter);
        }
    }
}
