//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Payable
    {
        public int Invoice_Number { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Ticket_Number { get; set; }
        public string Description { get; set; }
        public string Routing { get; set; }
        public Nullable<decimal> Net_Payable { get; set; }
        public Nullable<decimal> Paid2 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Payable_Supplier { get; set; }
        public string Payable_Code { get; set; }
        public string Air_ID { get; set; }
        public string Pay_Status { get; set; }
    }
}
