//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VID { get; set; }
        public Nullable<int> Bank_ID { get; set; }
        public string Bank_Cash_Receiveable { get; set; }
        public string Payable_Code { get; set; }
        public string Exp_Code { get; set; }
        public Nullable<int> Cust_Code { get; set; }
        public Nullable<System.DateTime> Received_Paid_Date { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string DrCr { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
        public string Received_Paid { get; set; }
        public string User_Name { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AirLine AirLine { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DailyExpens DailyExpens { get; set; }
    }
}
